profil_index:
    path:     /
    defaults: { _controller: "UserBundle:User:index" }
    methods:  GET

profil_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:User:show" }
    methods:  GET

profil_new:
    path:     /new
    defaults: { _controller: "UserBundle:User:new" }
    methods:  [GET, POST]

profil_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:User:edit" }
    methods:  [GET, POST]

profil_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:User:delete" }
    methods:  DELETE
