wcs_property_professionnel:
    resource: "@WCSPropertyBundle/Resources/config/routing/professionnel.yml"
    prefix:   /{_locale}/professionnel
    defaults: {_locale: fr}

club-house:
    path:     /clubhouse/{profCode}
    defaults: {_controller: WCSPropertyBundle:Default:clubhouse }

putFavorites:
    path:     /clubhouse/{profCode}/favorites
    defaults: {_controller: WCSPropertyBundle:Default:favoris }

showMap:
    path:     /ShowMap
    defaults: {_controller: WCSPropertyBundle:ShowMap:ShowMap }
    options:
        expose: true

Etablissement:
    path:     /Etablissement
    defaults: {_controller: WCSPropertyBundle:ShowEtablissement:Etablissement }
    options:
        expose: true

SortingEtablissement:
    path:     /SortingEtablissement
    defaults: {_controller: WCSPropertyBundle:ShowEtablissement:SortingEtablissement }
    options:
        expose: true

StarEtablissement:
    path:     /StarEtablissement
    defaults: {_controller: WCSPropertyBundle:ShowEtablissement:StarEtablissement }
    options:
        expose: true
