wcs_property_professionnel:
    resource: "@WCSPropertyBundle/Resources/config/routing/professionnel.yml"
    prefix:   /{_locale}/professionnel

club-house:
    path:     /{_locale}/clubhouse/{profCode}
    defaults: {_controller: WCSPropertyBundle:Default:clubhouse }

putFavorites:
    path:     /{_locale}/clubhouse/{profCode}/favorites
    defaults: {_controller: WCSPropertyBundle:Default:favoris }

showMap:
    path:     /fr/ShowMap
    defaults: {_controller: WCSPropertyBundle:ShowMap:ShowMap }
    options:
        expose: true

Etablissement:
    path:     /fr/Etablissement
    defaults: {_controller: WCSPropertyBundle:ShowEtablissement:Etablissement }
    options:
        expose: true

SortingEtablissement:
    path:     /fr/SortingEtablissement
    defaults: {_controller: WCSPropertyBundle:ShowEtablissement:SortingEtablissement }
    options:
        expose: true

StarEtablissement:
    path:     /fr/StarEtablissement
    defaults: {_controller: WCSPropertyBundle:ShowEtablissement:StarEtablissement }
    options:
        expose: true
